In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 1.75444609 -0.75373794 -0.06723197 -0.0606818   0.74910845]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 1.75444609 -0.75373794 -0.06723197 -0.0606818   0.74910845]


In [5]:
print(np.dot(a, a.T))

4.215567866746028


In [6]:
a = np.random.randn(5, 1)
print(a)

[[-0.56834827]
 [ 0.47985513]
 [ 0.59213327]
 [ 0.55503013]
 [ 0.61599113]]


In [7]:
print(a.T)

[[-0.56834827  0.47985513  0.59213327  0.55503013  0.61599113]]


In [8]:
print(np.dot(a, a.T))

[[ 0.32301975 -0.27272483 -0.33653792 -0.31545041 -0.35009749]
 [-0.27272483  0.23026095  0.28413819  0.26633406  0.29558651]
 [-0.33653792  0.28413819  0.3506218   0.3286518   0.36474884]
 [-0.31545041  0.26633406  0.3286518   0.30805845  0.34189364]
 [-0.35009749  0.29558651  0.36474884  0.34189364  0.37944507]]


- Don't use `rank 1 array`
```python
a.shape = (5,)
a = np.random.randn(5)
```

- Use assert or reshape
```python
assert(a.shape == (5,1))
a = a.reshape((5,1))
```